project_id = "qrvyjpgypceakznddmxf"

[functions.list-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-ai]
verify_jwt = false
