// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-objetivos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function env(name) {
  const g = globalThis;
  const v = g.process?.env?.[name] ?? g.Deno?.env?.get(name);
  if (!v) throw new Error(`Missing env: ${name}`);
  return v;
}
function sbForUser(ctx) {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-objetivos.ts
var list_objetivos_default = defineTool({
  name: "list_objetivos",
  title: "Listar Objetivos (OKR)",
  description: "Lista os objetivos OKR do usu\xE1rio autenticado, opcionalmente filtrando por ciclo.",
  inputSchema: {
    ciclo: z.string().optional().describe("Ciclo/per\xEDodo do OKR, ex: '2026.1'"),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ ciclo, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("okr_objetivos").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (ciclo) q = q.eq("ciclo", ciclo);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { objetivos: data } };
  }
});

// src/lib/mcp/tools/list-key-results.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_key_results_default = defineTool2({
  name: "list_key_results",
  title: "Listar Key Results",
  description: "Lista Key Results, opcionalmente filtrando por objetivo, l\xEDder ou equipe.",
  inputSchema: {
    objetivo_id: z2.string().uuid().optional(),
    lider: z2.string().optional(),
    equipe: z2.string().optional(),
    limit: z2.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ objetivo_id, lider, equipe, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("okr_key_results").select("*").limit(limit ?? 100);
    if (objetivo_id) q = q.eq("objetivo_id", objetivo_id);
    if (lider) q = q.ilike("lider", `%${lider}%`);
    if (equipe) q = q.ilike("equipe", `%${equipe}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { key_results: data } };
  }
});

// src/lib/mcp/tools/list-acoes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_acoes_default = defineTool3({
  name: "list_acoes",
  title: "Listar A\xE7\xF5es de KR",
  description: "Lista a\xE7\xF5es do plano de KR, filtr\xE1veis por key_result_id, respons\xE1vel ou status.",
  inputSchema: {
    key_result_id: z3.string().uuid().optional(),
    responsavel: z3.string().optional(),
    status: z3.string().optional().describe("Ex: 'A iniciar', 'Em andamento', 'Conclu\xEDdo', 'Atrasado'"),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ key_result_id, responsavel, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("okr_acoes").select("*").order("numero", { ascending: true }).limit(limit ?? 200);
    if (key_result_id) q = q.eq("key_result_id", key_result_id);
    if (responsavel) q = q.ilike("responsavel", `%${responsavel}%`);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { acoes: data } };
  }
});

// src/lib/mcp/tools/list-reunioes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_reunioes_default = defineTool4({
  name: "list_reunioes",
  title: "Listar Reuni\xF5es",
  description: "Lista reuni\xF5es do usu\xE1rio autenticado, opcionalmente filtrando por status.",
  inputSchema: {
    status: z4.string().optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("reunioes").select("*").order("data", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { reunioes: data } };
  }
});

// src/lib/mcp/tools/list-decisoes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_decisoes_default = defineTool5({
  name: "list_decisoes",
  title: "Listar Decis\xF5es",
  description: "Lista decis\xF5es estrat\xE9gicas registradas.",
  inputSchema: {
    status: z5.string().optional(),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("decisoes").select("*").order("data", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { decisoes: data } };
  }
});

// src/lib/mcp/tools/create-decisao.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^4.4.3";
var create_decisao_default = defineTool6({
  name: "create_decisao",
  title: "Registrar Decis\xE3o",
  description: "Cria uma nova decis\xE3o no Hub de Governan\xE7a em nome do usu\xE1rio autenticado.",
  inputSchema: {
    tema: z6.string().min(1),
    decisao: z6.string().optional(),
    justificativa: z6.string().optional(),
    impacto: z6.string().optional(),
    responsavel: z6.string().optional(),
    data: z6.string().optional().describe("Data no formato ISO (YYYY-MM-DD)"),
    status: z6.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sbForUser(ctx).from("decisoes").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Decis\xE3o criada: ${data.id}` }], structuredContent: { decisao: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qrvyjpgypceakznddmxf";
var mcp_default = defineMcp({
  name: "hub-governanca-sefin-mcp",
  title: "Hub de Governan\xE7a SEFIN",
  version: "0.1.0",
  instructions: "Ferramentas para consultar OKRs (objetivos, key results, a\xE7\xF5es), reuni\xF5es e decis\xF5es do Hub de Governan\xE7a da SEFIN, e registrar novas decis\xF5es. Cada chamada age em nome do usu\xE1rio autenticado e respeita as pol\xEDticas de acesso (RLS) do sistema.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_objetivos_default, list_key_results_default, list_acoes_default, list_reunioes_default, list_decisoes_default, create_decisao_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
